### ISSUE TITLE
[BUG] Some packaging issues with 1.0.2

### ISSUE THREAD

**Issue by jamesliupenn** [onfleet/pyonfleet#12]
**Describe the bug**
Users have reported that config file folder wasn't included in 1.0.2

**To Reproduce**
1. Fresh install of pyonfleet 1.0.2
2. `FileNotFoundError: [Errno 2] No such file or directory: ‘config/config.json’`

**Expected behavior**
config folder to be installed

**Additional context**
Add any other context about the problem here, including `pyonfleet` version and request ID that returned on your error response.

**Comment by cesarmarroquin** [comment]
I also reproduced this error while doing a fresh install of pyonfleet version 1.0.2.

**Comment by jamesliupenn** [comment]
This should be fixed in 1.1.0, closing
