### ISSUE TITLE
[BUG] Sometimes backend doesn't send message

### ISSUE THREAD

**Issue by bbradshaw** [onfleet/pyonfleet#14]
Certain types of errors, like 405 MethodNotAllowed, are incorrectly handled.  The assumption is that the server will send a JSON encoded object with this shape:
`{"code":"...","message":{error:"...", code: "..", "message"..."}}`

But the backend is not consistent and this shape is sometimes found (actual response):
`{"code":"MethodNotAllowed","message":"POST is not allowed"}'`

This causes a TypeError in the error handling routine of request.py:56.

```
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
string indices must be integers
  File "/Users/ben/Documents/testing_scripts/test_venv/lib/python3.9/site-packages/onfleet/request.py", line 56, in __call__
    error_code = error["message"]["error"]
...
```

**Comment by bbradshaw** [comment]
Oops, i meant the title to be "Message as object".  But you get the gist :)

**Comment by jamesliupenn** [comment]
https://github.com/onfleet/pyonfleet/pull/15 has been merged and released on PyPI
