### ISSUE TITLE
Add 'error cause' when raising HttpError exception on Request class

### ISSUE THREAD

**Issue by saduqz** [onfleet/pyonfleet#19]
Actually, the Request class raises the exception HttpError with `error_message`, `error_code`, `error_request` but it's not returning the error cause. There is no way to know if the issue is the **phone number** of a **geocoding error**.

This information is on `error["message"]["cause"]` but it's not returned in the exception and it's not easy to know what should be fixed.

I should suggest adding the argument `cause` or `reason` into the `HttpError` class.

I can create a PR for that, but I would like to know your thoughts before.

**Comment by jamesliupenn** [comment]
@saduqz We've created an internal ticket tracking this enhancement request, feel free to submit a PR if you happen to get to it!

**Comment by saduqz** [comment]
Hi @jamesliupenn 

I just created the PR: https://github.com/onfleet/pyonfleet/pull/20

Let me know your thoughts.

Regards, and thank you so much.

**Comment by saduqz** [comment]
Hi @jamesliupenn 

It looks like this enhancement is generating some issues when the key "cause" doesn't exists in `error["message"]`

So, instead `error_cause = error["message"]["cause"]` I'm proposing `error["message`"].get("cause")` in the PR #22

**Comment by saduqz** [comment]
Hi @jamesliupenn 

Is possible to make an update into pipy with the new changes implemented in PR #22?

**Comment by jamesliupenn** [comment]
Sure thing, will schedule that for this week

**Comment by jamesliupenn** [comment]
@saduqz this has been pushed to PyPI in v1.1.4, thanks for the contribution!
